apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask
    tier: frontend
  name: elk-web
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30010
  selector:
    app: flask
    tier: frontend
status:
  loadBalancer: {}
