---
- hosts: containers
  vars:
    max_clients: 10
  remote_user: root
  tasks:
  - name: check if "python" is present
    yum:
      name: python
      state: present
  - name: check if "sendmail" is installed
    yum:
      list: sendmail
    register: sendmail_installed
  - name: install "sendmail" if it does not exist
    yum:
      name: sendmail
      state: latest
    when:  (sendmail_installed.results|length == 1) or (sendmail_installed.results[1].yumstate != 'installed')
        