version: "3"
services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/local/pytools
  neo4j:
    restart: always
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    ports: 
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
    
