version: "3"
services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/local/pytools
    tty: true
    command: python /usr/local/pytools/tensorflow-mnist-tutorial/mnist_1.0_softmax.py
