version: "3"
services:
  ansible:
    build:
      context: ./host
      dockerfile: Dockerfile
    volumes:
      - ./host/etc/ansible/hosts:/etc/ansible/hosts
      - ./host/etc/ansible/ansible.cfg:/etc/ansible/ansible.cfg
    stdin_open: true
    container_name: ansible
    links: 
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "22:22"
    volumes: 
      - ./client/etc/ssh:/root/.ssh
    stdin_open: true
    container_name: client
    command: ["/usr/sbin/sshd", "-D"]